import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = process.cwd();
const input = resolve(root, 'cdm.json');
const output = resolve(root, 'src/generated/cdm.ts');
const empty = { registry: '', dependencies: {}, contracts: {} };
let manifest = empty;

if (existsSync(input)) {
  try {
    manifest = JSON.parse(readFileSync(input, 'utf8'));
  } catch (error) {
    console.warn('[PolkaCrew] cdm.json could not be parsed; contract integration will be disabled.', error);
  }
}

mkdirSync(dirname(output), { recursive: true });
writeFileSync(
  output,
  `// Generated by scripts/sync-cdm.mjs. Do not edit by hand.\nconst cdm = ${JSON.stringify(manifest, null, 2)} as const;\nexport default cdm;\n`,
);

const installed = Boolean(manifest?.contracts?.['@w3nerick/polkacrew-results']);
console.log(`[PolkaCrew] CDM manifest: ${installed ? 'PolkaCrewResults installed' : 'contract not installed; local/off-chain settlement only'}`);
